config/routes.rb
Rails.application.routes.draw do
  concern :searchable, Blacklight::Routes::Searchable.new

  root to: redirect("/#{Settings.default_publication}")

  resource :search, only: [:index], controller: 'catalog', as: 'catalog' do
    concerns :searchable
  end

  # scope ":publication" do
  #   resource :search, only: [:index], controller: 'catalog', as: 'catalog' do
  #     concerns :searchable
  #   end
  # end
  
  # get '/browse' => 'catalog#browse', as: :browse
  # get '/search' => 'catalog#search', as: :

  get '/:publication/browse' => 'catalog#browse', as: :browse
  get '/:publication/search' => 'catalog#index', as: :search
  
  get '/browse', to: redirect { |params, request| "/midaily/browse?#{request.params.to_query}" }
  get '/search', to: redirect { |params, request| "/midaily/search?#{request.params.to_query}" }

  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout'}, controllers: {sessions: 'sessions'}
  get '/logout_now', to: 'sessions#logout_now'
  get '/go_back', to: 'sessions#go_back'
  get '/login_info', to: 'sessions#login_info'
  
  if true

    constraints = { volume_identifier: /[^\/]+/, volume_sequence: /\d+/ }

    # --- this is of minimal use
    # get '/:publication/:volume_identifier' => 'catalog#volume',
    #   constraints: constraints

    # get '/:publication/:issue_identifier' => 'catalog#index',
    #   constraints: { issue_identifier: /[^\/]+/ }

    get '/:publication/:volume_identifier/:volume_sequence' => 'catalog#show',
      constraints: constraints

    post '/:publication/:volume_identifier/:volume_sequence/toggle_highlight' => 'catalog#toggle_highlight',
      constraints: constraints #, as: :toggle_highlight_solr_document

    get '/:publication/:volume_identifier/:volume_sequence/download_issue_text' => 'catalog#download_issue_text',
      constraints: constraints #, as: :download_issue_text_solr_document

    get '/:publication/:volume_identifier/:volume_sequence/download_text' => 'catalog#download_text',
      constraints: constraints #, as: :download_text_solr_document

    get '/:publication/:volume_identifier/:volume_sequence/issue_data' => 'catalog#issue_data',
      constraints: constraints #, as: :issue_data_solr_document

  end

  if false
    resources :solr_documents, only: [:show], path: '/pages', controller: 'catalog',
      constraints: { id: /[^\/]+/ }  do
      member do
        post 'toggle_highlight'
        get 'download_text'
        get 'download_issue_text'
        get 'issue_data'
      end
    end
  end

  # redirect old static links for daily to new daily locations
  get '/static/donors', to: redirect('/midaily/donors')
  get '/static/about_project', to: redirect('/midaily/project')
  get '/static/daily_about', to: redirect('/midaily/about')
  get '/static/rights', to: redirect('/midaily/rights')
  get '/static/about_daily', to: redirect('/midaily/project')

  get '/static/how_to_search', to: redirect('/midaily/how_to_search')
  get '/static/using_page_viewer', to: redirect('/midaily/using_page_viewer')

  post 'static/search' => 'static#search'

  get '/:publication/:page', to: 'static#show'

  #get 'static/:action' => 'static', as: :static

  get 'services/manifests/:id'  => 'services_api#manifests', as: :services_manifests, format: false, defaults: { format: :json }
  get 'services/annotations/:id' => 'services_api#annotations', as: :services_annotations, format: false, defaults: { format: :json }
  get 'services/coords/:id' => 'services_api#coords', as: :services_coords, format: false, defaults: { format: :json }

  get '/:publication', to: 'catalog#home', as: 'publication_home'

end

app/controllers/catalog_controller.rb
# frozen_string_literal: true
class CatalogController < ApplicationController
  include BlacklightAdvancedSearch::Controller

  # include BlacklightRangeLimit::ControllerOverride

  include Blacklight::Catalog
  include Fishrappr::Catalog

  helper Fishrappr::ControllerOverride

  layout :resolve_layout


  configure_blacklight do |config|
    # default advanced config values
    config.advanced_search ||= Blacklight::OpenStructWithHashAccess.new
    # config.advanced_search[:qt] ||= 'advanced'
    config.advanced_search[:url_key] ||= 'advanced'
    #config.advanced_search[:query_parser] ||= 'dismax'
    config.advanced_search[:query_parser] ||= 'edismax'
    config.advanced_search[:form_solr_parameters] ||= {}

    # config.add_results_document_tool(:bookmark, partial: 'bookmark_control', if: :render_bookmarks_control?)

    config.add_results_collection_tool(:sort_widget)
    config.add_results_collection_tool(:per_page_widget)
    config.add_results_collection_tool(:view_type_group)

    # config.add_show_tools_partial(:bookmark, partial: 'bookmark_control', if: :render_bookmarks_control?)
    # config.add_show_tools_partial(:email, callback: :email_action, validator: :validate_email_params)
    # config.add_show_tools_partial(:sms, if: :render_sms_action?, callback: :sms_action, validator: :validate_sms_params)
    # config.add_show_tools_partial(:citation)

    config.add_nav_action(:bookmark, partial: 'blacklight/nav/bookmark', if: :render_bookmarks_control?)
    config.add_nav_action(:search_history, partial: 'blacklight/nav/search_history')    

    ## Class for sending and receiving requests from a search index
    # config.repository_class = Blacklight::Solr::Repository
    #
    ## Class for converting Blacklight's url parameters to into request parameters for the search index
    # config.search_builder_class = ::SearchBuilder
    #
    ## Model that maps search index responses to the blacklight response model
    # config.response_model = Blacklight::Solr::Response
    config.document_presenter_class = Fishrappr::DocumentPresenter

    # Add actions for splash, about, and donors pages
    # 14June17 GML Note that login is added via
    # app/views/_user_util_links partial
    config.add_nav_action(:search, partial: "shared/nav/search")    
    config.add_nav_action(:browse, partial: "shared/nav/browse")
    config.add_nav_action(:about, partial: "shared/nav/about")
    config.add_nav_action(:help, partial: "hared/nav/help")
    # config.add_nav_action(:contact, partial: "shared/nav/contact")


    config.index.collection_actions.delete(:view_type_group)
    config.index.collection_actions.delete(:per_page_widget)

    config.navbar.partials.delete(:bookmark)
    config.navbar.partials.delete(:saved_searches)
    config.navbar.partials.delete(:search_history)

    ## Default parameters to send to solr for all search-like requests. See also SearchBuilder#processed_parameters
    config.default_solr_params = {
      rows: 50,
      :qt => 'search',
      :qf => [ 'page_text', 'page_text_unstemmed^100000' ],
      :hl => true,
      :"hl.fragsize" => 200,
      :"hl.fl" => 'page_text',
      :"hl.snippets" => 10,
      :"hl.alternateField" => 'page_abstract',
      :"hl.simple.pre" => '[[[[',   # change to something accessible
      :"hl.simple.post" => ']]]]', # change to something accessible
      fl: [
            'id',
            'page_identifier',
            'issue_identifier',
            'volume_identifier',
            'issue_sequence',
            'volume_sequence',
            'variant_sequence',
            'text_link',
            'image_link',
            'coordinates_link',
            'image_height_ti',
            'image_width_ti',
            'date_issued_display',
            'publication_link',
            'publication_label',
            'issue_no_t',
            'page_no_t',
            'issue_vol_iss_display',
            'page_abstract',
            'score',
          ].join(',')
    }

    # solr path which will be added to solr base url before the other solr params.
    #config.solr_path = 'select'

    # items to show per page, each number in the array represent another option to choose from.
    #config.per_page = [10,20,50,100]
    config.per_page = [ 50, 100 ]

    ## Default parameters to send on single-document requests to Solr. These settings are the Blackligt defaults (see SearchHelper#solr_doc_params) or
    ## parameters included in the Blacklight-jetty document requestHandler.
    #
    config.default_document_solr_params = {
     qt: 'document',
    #  ## These are hard-coded in the blacklight 'document' requestHandler
     fl: '*',
     rows: 1,
     q: '{!term f=id v=$id}'
    }

    ### DO WE NEED THESE
    # config.document_index_view_types = ["default", "gallery", "list", "frequency", "covers"]
    # config.view.grid.partials = [:index]
    # config.view.grid.icon_class = "glyphicon-th-large"

    # solr field configuration for search results/index views
     config.index.title_field = 'date_issued_display'
#    config.index.page_no_field = 'page_no_t'

    # solr field configuration for document/show views
     config.show.title_field = 'date_issued_display'
#    config.show.date_issued_field = 'date_issued_t'
#    config.index.page_no_field = 'page_no_t'


    # solr fields that will be treated as facets by the blacklight application
    #   The ordering of the field names is the order of the display
    #
    # Setting a limit will trigger Blacklight's 'more' facet values link.
    # * If left unset, then all facet values returned by solr will be displayed.
    # * If set to an integer, then "f.somefield.facet.limit" will be added to
    # solr request, with actual solr request being +1 your configured limit --
    # you configure the number of items you actually want _displayed_ in a page.
    # * If set to 'true', then no additional parameters will be sent to solr,
    # but any 'sniffed' request limit parameters will be used for paging, with
    # paging at requested limit -1. Can sniff from facet.limit or
    # f.specific_field.facet.limit solr request params. This 'true' config
    # can be used if you set limits in :default_solr_params, or as defaults
    # on the solr side in the request handler itself. Request handler defaults
    # sniffing requires solr requests to be made with "echoParams=all", for
    # app code to actually have it echo'd back to see it.
    #
    # :show may be set to false if you don't want the facet to be drawn in the
    # facet bar
    #
    # set :index_range to true if you want the facet pagination view to have facet prefix-based navigation
    #  (useful when user clicks "more" on a large facet and wants to navigate alphabetically across a large set of results)
    # :index_range can be an array or range of prefixes that will be used to create the navigation (note: It is case sensitive when searching values)

    # config.add_facet_field 'date_issued_dt', label: 'Issue Date', helper_method: :render_date_format
    # # config.add_facet_field 'issue_no_t', label: 'Issue No'
    # config.add_facet_field 'date_issued_yyyy_ti', label: 'Issue Year', range: true
    # config.add_facet_field 'date_issued_yyyymmdd_ti', label: 'Date Range', range: {
    #                      num_segments: 10,
    #                      maxlength: 4
    #                    }
    # # seg was 6, len was 8
    # config.add_facet_field 'issue_sequence', single: true

    config.add_facet_field 'issue_sequence_field', label: 'On Page', collapse: false,
        query: { issue_sequence_1: { label: 'Front Page', fq: 'issue_sequence:1' } }
    config.add_facet_field 'date_issued_yyyy10_ti', label: 'Decade', sort: 'index', limit: 20, collapse: false
    config.add_facet_field 'date_issued_yyyy_ti', label: 'Year', sort: 'index', limit: 20
    config.add_facet_field 'date_issued_mm_ti', label: 'Month', sort: 'index', helper_method: :get_month_label
    config.add_facet_field 'date_issued_dd_ti', label: 'Day', sort: 'index', limit: 20
    config.add_facet_field 'date_issued_yyyymmdd_ti', label: 'Date', show: false
    config.add_facet_field 'issue_identifier', label: 'Issue', show: false

    # Have BL send all facet field names to Solr, which has been the default
    # previously. Simply remove these lines if you'd rather use Solr request
    # handler defaults, or have no facets.
    config.add_facet_fields_to_solr_request!

    # solr fields to be displayed in the index (search results) view
    #   The ordering of the field names is the order of the display
    #config.add_index_field 'date_issued_dt', label: 'Issue Date'
    config.add_index_field 'date_issued_display', label: ''
    config.add_index_field 'issue_no_t', label: 'Issue'
    #config.add_index_field 'page_no_t', label: 'Page'
    config.add_index_field 'issue_sequence', label: 'Image Number'
    config.add_index_field 'page_text', label: '' , highlight: true, separator_options: { words_connector: ' ... '}

    # solr fields to be displayed in the show (single result) view
    #   The ordering of the field names is the order of the display
    config.add_show_field 'issue_no_t', label: 'Issue'
    config.add_show_field 'date_issued_display', label: 'Date'
    config.add_show_field 'page_no_t', label: 'Page No'
    config.add_show_field 'issue_sequence', label: 'Image Number'
    config.add_show_field 'page_text', label: 'Page Text'

    config.add_show_field 'next_page_link', label: 'Next Page Link'
    config.add_show_field 'next_page_label', label: 'Next Page Label'
    config.add_show_field 'prev_page_link', label: 'Previous Page Link'
    config.add_show_field 'prev_page_label', label: 'Previous Page Label'

    #config.add_show_field 'img_link_t', label: 'Image', helper_method: :hathitrust_image_src(document)

    # "fielded" search configuration. Used by pulldown among other places.
    # For supported keys in hash, see rdoc for Blacklight::SearchFields
    #

app/helpers/catalog_helper.rb
# frozen_string_literal: true
module CatalogHelper
  include Blacklight::CatalogHelperBehavior

  def render_search_to_page_title(params)
    constraints = []

    if params['q'].present?
      q_label = label_for_search_field(params[:search_field]) unless blacklight_config.default_search_field && params[:search_field] == blacklight_config.default_search_field[:key]

      constraints += if q_label.present?
                       [t('blacklight.search.page_title.constraint', label: q_label, value: params['q'])]
                     else
                       [params['q']]
                     end
    end

    if params['f'].present?
      constraints += params['f'].to_unsafe_h.collect { |key, value| render_search_to_page_title_filter(key, value) }
    end

    retval = constraints.join(' / ')
    unless retval.blank?
      retval += " - "
    end
    retval
  end
end

app/views/publications/spokesman/views/catalog/_home_header_navbar.html.erb
<div class="border-bottom">
  <m-universal-header></m-universal-header>
  <m-website-header name="Digital Collections" to="https://quod.lib.umich.edu">
    <%= render :partial=>'/user_util_links' %>  
  </m-website-header>
</div>

app/views/publications/spokesman/views/catalog/_panel_action_rights.html.erb
      <div class="panel panel-actions-rights">
        <div class="panel-heading">
          <h3>Rights / Permissions</h3>
        </div>
        <div class="panel-body">
          <p>The University of Michigan Library provides access to these materials for educational and research purposes. These materials may be under copyright. If you decide to use any of these materials, you are responsible for making your own legal assessment and securing any necessary permission. If you have questions about the collection, please contact the Bentley Historical Library at <a href="mailto:bentley.ref@umich.edu">bentley.ref@umich.edu</a></p>
          <p class="xx-see-more" role="alert">
            If you have non-permissions questions about the collection, please use the <a href="<%= contacts_path type: 'content' %>">contact form</a>. If you have concerns about the inclusion of an item in this collection, please contact <a href="mailto:LibraryIT-info@umich.edu">LibraryIT-info@umich.edu</a>.
          </p>
        </div>
      </div>

app/views/publications/spokesman/views/catalog/_show_header_default.html.erb
<h1 class="viewer-header">
    <%= issue_title(document, true) %>
    - 
     Image <%= current_image_sequence(document) %>
</h1>
<dl class="dl-horizontal">
    <dt>Resource type:</dt>
    <dd>Text</dd>
    <dt>Publication:</dt>
    <dd><%= document.fetch('publication_label') %></dd>
    <% if document.fetch('page_no_t', []).first %>
    <dt>Page Number:</dt>
    <dd><%= document.fetch('page_no_t').first %></dd>
    <% end %>
    <!-- <dt>Division:</dt>
    <dd>Bentley Historical Library</dd> -->
    <% if document.fetch('page_label', nil) == 'tabloid' %>
    <dt>Note:</dt>
    <dd><span class="label label-note">This is a <a href="<%= fishrappr_path('using_page_viewer') %>#tabloid-pages" target="_blank">tabloid page</a></dd></dd>
    <% end %>
</dl>
<hr />

app/views/publications/spokesman/views/catalog/browse.html.erb
<%= replace :skiplinks do %>
  <%= render 'browse_skiplinks' %>
<% end %>

<% purge :h1_wrap %>

<div class="col-sm-12" id="browse-form">

  <% decade_browse_options = get_decade_browse_options %>
  <% year_browse_options = get_year_browse_options %>
  <% month_browse_options = get_month_options; month_browse_options.unshift(['Any Month', 'Any Month']) %>
  <% date_browse_options = get_date_options; date_browse_options.unshift(['Any Day', 'Any Day']) %>
  <% first_year_to_browse = year_browse_options.last.first %>

  <div class="[ uplift-breadcrumb ]">
    <nav aria-label="Breadcrumb" style="padding: 0">
      <ol>
        <li>
          <a class="btn btn-link" href="<%= publication_root_url %>">The Flint Spokesman</a>
        </li>
        <li class="active">
          <span aria-current="page" class="current-image-sequence">Browse Issues</span>
        </li>
      </ol>
    </nav>
  </div>

  <h1>Browse Issues</h1>
  <h2 class="browse-subtitle">Browse <%= @publication.title %> Issues back to <%= first_year_to_browse %></h2>

  <p class="browse-instructions">Select a decade, year, month or day to browse issues</p>

    <%= form_tag(browse_path, role: 'search', method: :get, class: "form-inline browse-form") do %>
      <div class="browse-select-box" aria-live="polite">
        <div class="form-group">
          <%=  label_tag 'date_issued_yyyy10_ti', 'Filter by decade', class: 'sr-only' %>
          <%= select_tag(name="date_issued_yyyy10_ti", options_for_select(decade_browse_options, params[:date_issued_yyyy10_ti]), class: 'changeable form-control') %>          
          <%=  label_tag 'date_issued_yyyy_ti', 'Filter by year', class: 'sr-only' %>
          <%= select_tag(name="date_issued_yyyy_ti", options_for_select(year_browse_options, params[:date_issued_yyyy_ti]), class: 'changeable form-control') %>
          <%=  label_tag 'date_issued_mm_ti', 'Filter by month', class: 'sr-only' %>
          <%= select_tag(name="date_issued_mm_ti", options_for_select(month_browse_options, params[:date_issued_mm_ti]), class: 'changeable form-control') %>
          <%=  label_tag 'date_issued_dd_ti', 'Filter by day', class: 'sr-only' %>
          <%= select_tag(name="date_issued_dd_ti", options_for_select(date_browse_options, params[:date_issued_dd_ti]), class: 'changeable form-control') %>
          <button type="submit" class="btn btn-action btn-lg" xid="browse">
            <span class="<%= use_icon_class('search') %>"></span>
            <span class="hidden <%= use_icon_class('rotate_left') %> glyphicon-refresh-animate"></span> 
            <span class="submit-browse-text">Browse</span>
          </button>
        </div>
      </div>
    <% end %>
</div>
<h2 class="sr-only">Browse Results</h2>
<div class="col-sm-12">
  <div class="issues-display">

    <!-- alternative: render search_results %>
    <!-- alternative: render results_pagination -->

    <% if @response.total_pages == 0 %>
      <p><em>No issues were found.</em>
    <% else %>

      <div class="row record-padding">
        <div class="col-md-12">
          <div class="pagination">
            <%= render :partial => "paginate_compact", :object => @response if show_pagination? %>
          </div>
        </div>
      </div>

      <div id="groups">
        <%- @response.groups.each do |g| %>
          <h3 class="group-key browse-month-group"><%= Date.strptime(g.key.to_s, "%Y%m").strftime("%B %Y") %> (<%= pluralize(g.total, 'issue') %>)</h3>
          <div class="grouped-documents">
            <%= render_document_index g.docs %>
          </div>
          <%- if g.total > @response.group_limit %>
            <%= link_to t('blacklight.search.group.more'), add_group_facet_params_and_redirect(g), :class => 'more-in-group' %>
          <%- end %>
        <%- end %>
      </div>

      <% if false %>
      <div class="row record-padding">
        <div class="col-md-12">
          <div class="pagination">
            <%= render :partial => "paginate_compact", :object => @response if show_pagination? %>
          </div>
        </div>
      </div>
      <% end %>
      <%= render partial: 'results_pagination' %>

    <% end %>

  </div>
</div>

<%= render partial: 'back_to_top' %>

app/views/publications/spokesman/views/catalog/home.html.erb
<div class="home container-fluid">
    <div class="head head-micitizen col-md-12">
      <h1>The Flint Spokesman
        <span class="subtitle"><%= t('views.spokesman-static.home.head.page_title') %></span>
      </h1>
      <p class="description1"><%= fill_publication_details(t('views.spokesman-static.home.head.subtitle1')) %></p>
      <p class="description2"></p>
      <p class="description3">&nbsp;</p>
      <a href="/<%= "#{@publication['slug']}" %>/about"><%= t('views.spokesman-static.home.head.link') %></a>
      <% if true %><%= render partial: "search_form", locals: { container_class: 'container' } %><% end %>
      <!-- <p class="description4"><%= t('views.spokesman-static.home.head.description3') %></p> -->
    </div>
</div>
<div class="home container-fluid">
  <div class="partnerships col-md-12">
    <p>In Partnership With</p>
    <ol class="partnerships-list">
      <% if false %>
      <li><%= link_to(image_tag("DJNews-Archive-Logo.png", :alt => "The Detroit Jewish News"), 'https://thejewishnews.com/', class: 'djnews-logo') %></li>
      <li><%= link_to(image_tag("DJNfoundation-logo.png", :alt => "Detroit Jewish News Foundation"), 'https://djnfoundation.org', class: 'djnews-foundation-logo') %></li>
      <% end %>
      <li><%= link_to(image_tag("u-m_library_logo.png", :alt => "University of Michigan Library"), 'https://lib.umich.edu', class: 'mlibrary-logo') %></li>
      <li><%= link_to(image_tag("u-m_flint_library_logo.png", :alt => "University of Michigan Flint Frances Wilson Thompson Library"), 'https://libguides.umflint.edu/library', class: 'mlibrary-logo') %></li>
    </ol>
  </div>
</div>
<div class="home container-fluid">
    <div class="featured col-md-12">
      <h2 class="featured-title"><%= t('views.spokesman-static.home.today.title') %></h2>
      <p class="description"><%= @featured_list.first["date_issued_display"].first.split(",").first if @featured_list.first %></p>
      <div id="documents" class="row grid">
        <% @featured_list.each do |document| %>
          <a href="<%= url_for url_for_document(document) %>" style="display: block;">
              <figure data-identifier="<%= document.id %>">
                  <div class="thumbnail" style=" <%= document_thumbnail_style(document, size: '256,') %>">
                    <%= document_thumbnail(document, size: '256,') %>
                  </div>
                  <figcaption>
                    <%= document.fetch(:date_issued_display).first %>
                  </figcaption>
              </figure>
          </a>
        <% end %>
      </div>
      <%= link_to t('views.spokesman-static.home.today.link'), browse_path(date_issued_mm_ti: @now.strftime("%-m"), date_issued_dd_ti: @now.strftime("%-d")), class: 'btn btn-default btn-squared' %>
    </div>
</div>

app/views/publications/spokesman/views/catalog/show.html.erb
<% @page_title = t('blacklight.show.page_title.title', date_issued: @document['date_issued_display'].first, issue_vol_iss: @document.fetch('issue_vol_iss_display', []).first, issue_sequence: @document['issue_sequence'], application_name: application_name) %>

<%= replace :head do %>
  <%= link_to_repository(@document) %>
  <%= link_to_manifest(@document) %>
  <%= render partial: 'document_share_metadata' %>
<% end %>

<%= replace :skiplinks do %>
  <%= render 'show_skiplinks' %>
<% end %>

<%= replace :data do %>data-option="<%= @option %>"<% end %>

<%= replace :search_navbar do %>
  <div class="[ uplift-breadcrumb ]">
    <nav aria-label="Breadcrumb" style="padding: 0">
      <ol>
        <li>
          <a class="btn btn-link" href="<%= publication_root_url %>">The Flint Spokesman</a>
        </li>
        <li>
          <a class="btn btn-link btn-issue-link" href="<%= search_catalog_url document_to_date_params(@document) %>">
            <span><%= issue_title(@document, true) %></span>
          </a>
        </li>
        <li class="active">
          <span aria-current="page" class="current-image-sequence">Page Image <%= current_image_sequence(@document) %></span>
        </li>
      </ol>
    </nav>
  </div>

  <div class="navigation-toolbar">
    <div class="container-fluid">
    <% if false %>
      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <h1 class="page">
            <span><%= publication_title(@document, @publication) %></span>
            <span class="pre-issue-mark"><%= use_icon('divider') %></span>
            <a class="btn btn-link btn-issue-link" href="<%= search_catalog_url document_to_date_params(@document) %>">
              <span><%= issue_title(@document, true) %></span> 
            </a>
            <span class="pre-page-mark"><%= use_icon('divider') %></span>
            <span class="current-image-sequence">Page Image <%= current_image_sequence(@document) %></span>
          </h1>
        </div>
      </div>
      <% end %>
      <div class="row">
        <div class="col-md-7 col-sm-7 col-xs-4 navigate-issue">
          <% if current_search_session %>
            <%= back_to_results_link class: 'btn btn-search-primary', label: back_to_results_label %>
          <% end %>
        </div>
        <div class="col-md-5 col-sm-5 col-xs-8 navigate-pages">
          <%= link_to_previous_issue_page @previous_page %>
          <span class="current-page-number"><span class="sr-only">Image </span><%= current_image_sequence(@document) %> of <%= @issue_data[:pages].size %></span>
          <%= link_to_next_issue_page @next_page %>
        </div>
      </div>
    </div>
  </div>
<% end %>

<%= render 'show_viewer_stacked_tabs' %>

<script>
$().ready(function() {
  $(".action-copy-permalink").on('click', function(e) {
    e.preventDefault();
    $("#permalink").select();
    document.execCommand('copy');
  });
  $("#action-rights-read-more").on('click', function(e) {
    e.preventDefault();
    var $div = $(this).parents("div");
    $div.find(".see-more").addClass("reading");
    $(this).hide();
    var y = window.scrollY;
    $("#action-rights-read-less").get(0).scrollIntoView();
    window.scrollTo(window.scrollX, y);
  });
  $("#action-rights-read-less").on('click', function(e) {
    e.preventDefault();
    var $div = $(this).parents("div");
    $div.find(".see-more").removeClass("reading");
    $("#action-rights-read-more").show();
  });

});
</script>
<%= render partial: 'back_to_top' %>